## Data cleaning

In [1]:
#importing the basics libraries required for data analysis 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly as py
import plotly.graph_objs as go
import ipywidgets as widgets
import plotly.offline as po
import dash
import dash_core_components as dcc
import dash_html_components as html
import json
import dash_bootstrap_components as dbc
import plotly.express as px
from dash.dependencies import Input,Output,State 
import seaborn as sns




In [2]:
#LEts now import the csv file

url="https://raw.githubusercontent.com/Sangram14/Global_Suicide-analysis-Project/main/dataset/dataset.csv"
df=pd.read_csv(url)


In [3]:
df.head()

country  year     sex          age  suicides_no  population  \
0  Albania  1987    male  15-24 years           21      312900   
1  Albania  1987    male  35-54 years           16      308000   
2  Albania  1987  female  15-24 years           14      289700   
3  Albania  1987    male    75+ years            1       21800   
4  Albania  1987    male  25-34 years            9      274300   

   suicides/100k pop country-year  HDI for year  gdp_for_year ($)   \
0               6.71  Albania1987           NaN      2,156,624,900   
1               5.19  Albania1987           NaN      2,156,624,900   
2               4.83  Albania1987           NaN      2,156,624,900   
3               4.59  Albania1987           NaN      2,156,624,900   
4               3.28  Albania1987           NaN      2,156,624,900   

   gdp_per_capita ($)       generation  
0                 796     Generation X  
1                 796           Silent  
2                 796     Generation X  
3                 796  G.I. Generation  
4                 796          Boomers

In [4]:
df.drop(['country-year','HDI for year','gdp_per_capita ($)'],axis=1,inplace=True)

In [5]:
del df[' gdp_for_year ($) ']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   country            27820 non-null  object 
 1   year               27820 non-null  int64  
 2   sex                27820 non-null  object 
 3   age                27820 non-null  object 
 4   suicides_no        27820 non-null  int64  
 5   population         27820 non-null  int64  
 6   suicides/100k pop  27820 non-null  float64
 7   generation         27820 non-null  object 
dtypes: float64(1), int64(3), object(4)
memory usage: 1.7+ MB


In [7]:
df.isna().sum()

country              0
year                 0
sex                  0
age                  0
suicides_no          0
population           0
suicides/100k pop    0
generation           0
dtype: int64

In [8]:
df.describe()

year   suicides_no    population  suicides/100k pop
count  27820.000000  27820.000000  2.782000e+04       27820.000000
mean    2001.258375    242.574407  1.844794e+06          12.816097
std        8.469055    902.047917  3.911779e+06          18.961511
min     1985.000000      0.000000  2.780000e+02           0.000000
25%     1995.000000      3.000000  9.749850e+04           0.920000
50%     2002.000000     25.000000  4.301500e+05           5.990000
75%     2008.000000    131.000000  1.486143e+06          16.620000
max     2016.000000  22338.000000  4.380521e+07         224.970000

In [9]:
dff=df.copy()

In [10]:
df.head()

country  year     sex          age  suicides_no  population  \
0  Albania  1987    male  15-24 years           21      312900   
1  Albania  1987    male  35-54 years           16      308000   
2  Albania  1987  female  15-24 years           14      289700   
3  Albania  1987    male    75+ years            1       21800   
4  Albania  1987    male  25-34 years            9      274300   

   suicides/100k pop       generation  
0               6.71     Generation X  
1               5.19           Silent  
2               4.83     Generation X  
3               4.59  G.I. Generation  
4               3.28          Boomers

In [11]:
dff.head()

country  year     sex          age  suicides_no  population  \
0  Albania  1987    male  15-24 years           21      312900   
1  Albania  1987    male  35-54 years           16      308000   
2  Albania  1987  female  15-24 years           14      289700   
3  Albania  1987    male    75+ years            1       21800   
4  Albania  1987    male  25-34 years            9      274300   

   suicides/100k pop       generation  
0               6.71     Generation X  
1               5.19           Silent  
2               4.83     Generation X  
3               4.59  G.I. Generation  
4               3.28          Boomers

In [12]:
print(df.shape)
type(df)

(27820, 8)


pandas.core.frame.DataFrame

## Removing the Outliers and Feature Selection

In [13]:
y=dff['suicides/100k pop']


In [14]:
type(y)

pandas.core.series.Series

In [15]:
y

0        6.71
1        5.19
2        4.83
3        4.59
4        3.28
         ... 
27815    2.96
27816    2.58
27817    2.17
27818    1.67
27819    1.46
Name: suicides/100k pop, Length: 27820, dtype: float64

In [16]:
dff

country  year     sex          age  suicides_no  population  \
0         Albania  1987    male  15-24 years           21      312900   
1         Albania  1987    male  35-54 years           16      308000   
2         Albania  1987  female  15-24 years           14      289700   
3         Albania  1987    male    75+ years            1       21800   
4         Albania  1987    male  25-34 years            9      274300   
...           ...   ...     ...          ...          ...         ...   
27815  Uzbekistan  2014  female  35-54 years          107     3620833   
27816  Uzbekistan  2014  female    75+ years            9      348465   
27817  Uzbekistan  2014    male   5-14 years           60     2762158   
27818  Uzbekistan  2014  female   5-14 years           44     2631600   
27819  Uzbekistan  2014  female  55-74 years           21     1438935   

       suicides/100k pop       generation  
0                   6.71     Generation X  
1                   5.19           Silent  
2                   4.83     Generation X  
3                   4.59  G.I. Generation  
4                   3.28          Boomers  
...                  ...              ...  
27815               2.96     Generation X  
27816               2.58           Silent  
27817               2.17     Generation Z  
27818               1.67     Generation Z  
27819               1.46          Boomers  

[27820 rows x 8 columns]

In [17]:
X=dff.copy()

In [18]:
X.drop(['suicides/100k pop','suicides_no','population','generation'],axis=1,inplace=True)

In [19]:
type(X)

pandas.core.frame.DataFrame

In [20]:
X

country  year     sex          age
0         Albania  1987    male  15-24 years
1         Albania  1987    male  35-54 years
2         Albania  1987  female  15-24 years
3         Albania  1987    male    75+ years
4         Albania  1987    male  25-34 years
...           ...   ...     ...          ...
27815  Uzbekistan  2014  female  35-54 years
27816  Uzbekistan  2014  female    75+ years
27817  Uzbekistan  2014    male   5-14 years
27818  Uzbekistan  2014  female   5-14 years
27819  Uzbekistan  2014  female  55-74 years

[27820 rows x 4 columns]

In [21]:
X.columns

Index(['country', 'year', 'sex', 'age'], dtype='object')

In [22]:
fig=px.scatter(X,y)
po.plot(fig)

'temp-plot.html'

In [23]:
X=X[y<60]
y=y[y<60]

In [24]:
fig=px.scatter(X,y)
po.plot(fig)

'temp-plot.html'

## Data Preprocessing

In [25]:
X=pd.get_dummies(X)
X

year  country_Albania  country_Antigua and Barbuda  country_Argentina  \
0      1987                1                            0                  0   
1      1987                1                            0                  0   
2      1987                1                            0                  0   
3      1987                1                            0                  0   
4      1987                1                            0                  0   
...     ...              ...                          ...                ...   
27815  2014                0                            0                  0   
27816  2014                0                            0                  0   
27817  2014                0                            0                  0   
27818  2014                0                            0                  0   
27819  2014                0                            0                  0   

       country_Armenia  country_Aruba  country_Australia  country_Austria  \
0                    0              0                  0                0   
1                    0              0                  0                0   
2                    0              0                  0                0   
3                    0              0                  0                0   
4                    0              0                  0                0   
...                ...            ...                ...              ...   
27815                0              0                  0                0   
27816                0              0                  0                0   
27817                0              0                  0                0   
27818                0              0                  0                0   
27819                0              0                  0                0   

       country_Azerbaijan  country_Bahamas  ...  country_Uruguay  \
0                       0                0  ...                0   
1                       0                0  ...                0   
2                       0                0  ...                0   
3                       0                0  ...                0   
4                       0                0  ...                0   
...                   ...              ...  ...              ...   
27815                   0                0  ...                0   
27816                   0                0  ...                0   
27817                   0                0  ...                0   
27818                   0                0  ...                0   
27819                   0                0  ...                0   

       country_Uzbekistan  sex_female  sex_male  age_15-24 years  \
0                       0           0         1                1   
1                       0           0         1                0   
2                       0           1         0                1   
3                       0           0         1                0   
4                       0           0         1                0   
...                   ...         ...       ...              ...   
27815                   1           1         0                0   
27816                   1           1         0                0   
27817                   1           0         1                0   
27818                   1           1         0                0   
27819                   1           1         0                0   

       age_25-34 years  age_35-54 years  age_5-14 years  age_55-74 years  \
0                    0                0               0                0   
1                    0                1               0                0   
2                    0                0               0                0   
3                    0                0               0                0   
4                    1                0               0                0   
...                ...         

In [26]:
X_df=X.copy()
Y_df=y.copy()
X=np.array(X)
y=np.array(y)

In [27]:
X

array([[1987,    1,    0, ...,    0,    0,    0],
       [1987,    1,    0, ...,    0,    0,    0],
       [1987,    1,    0, ...,    0,    0,    0],
       ...,
       [2014,    0,    0, ...,    1,    0,    0],
       [2014,    0,    0, ...,    1,    0,    0],
       [2014,    0,    0, ...,    0,    1,    0]], dtype=int64)

In [28]:
y

array([6.71, 5.19, 4.83, ..., 2.17, 1.67, 1.46])

## Applying the test- train split

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [30]:
X_train

array([[1987,    0,    0, ...,    0,    1,    0],
       [1990,    0,    0, ...,    0,    1,    0],
       [2002,    1,    0, ...,    0,    0,    0],
       ...,
       [2005,    0,    0, ...,    0,    1,    0],
       [1999,    0,    0, ...,    0,    0,    1],
       [2008,    0,    0, ...,    0,    0,    1]], dtype=int64)

In [31]:
y_train

array([26.22, 23.71,  5.7 , ..., 11.89,  4.68, 20.75])

In [32]:
X_test

array([[2004,    0,    0, ...,    0,    0,    0],
       [1996,    0,    0, ...,    0,    0,    0],
       [1995,    0,    0, ...,    0,    0,    0],
       ...,
       [2001,    0,    0, ...,    0,    1,    0],
       [2011,    0,    0, ...,    1,    0,    0],
       [2014,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [33]:
y_test

array([15.55, 18.37, 23.58, ..., 36.5 ,  0.55,  7.29])

### Linear Regression

In [34]:
from sklearn.linear_model import LinearRegression
lin_regressor = LinearRegression(fit_intercept=False)
lin_regressor.fit(X_train, y_train)

LinearRegression(fit_intercept=False)

In [35]:
y_pred_test = lin_regressor.predict(X_test)
y_pred_train = lin_regressor.predict(X_train)

from sklearn import metrics
rms_test = np.sqrt(metrics.mean_squared_error(y_test, y_pred_test))
rms_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred_train))

print('The RMSE of the training set is: ' + rms_train.astype(str))
print('The RMSE of the test set is: ' + rms_test.astype(str)) 

The RMSE of the training set is: 8.087104100064153
The RMSE of the test set is: 8.235141234652499


### Decision Tree Regression

In [36]:
from sklearn.tree import DecisionTreeRegressor
dt_regressor = DecisionTreeRegressor()
dt_regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [37]:
y_pred_test = dt_regressor.predict(X_test)
y_pred_train = dt_regressor.predict(X_train)

from sklearn import metrics
rms_test = np.sqrt(metrics.mean_squared_error(y_test, y_pred_test))
rms_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred_train))

print('The RMSE of the training set is: ' + rms_train.astype(str))
print('The RMSE of the test set is: ' + rms_test.astype(str)) 

The RMSE of the training set is: 6.566570319631823e-19
The RMSE of the test set is: 5.143302713092771


### Random Forest Regression

In [38]:
from sklearn.ensemble import RandomForestRegressor
rf_regressor = RandomForestRegressor(n_estimators=30)
rf_regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=30)

In [39]:
y_pred_test = rf_regressor.predict(X_test)
y_pred_train = rf_regressor.predict(X_train)

from sklearn import metrics
rms_test = np.sqrt(metrics.mean_squared_error(y_test, y_pred_test))
rms_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred_train))

print('The RMSE of the training set is: ' + rms_train.astype(str))
print('The RMSE of the test set is: ' + rms_test.astype(str)) 

The RMSE of the training set is: 1.6795928432965754
The RMSE of the test set is: 4.359439994854802


## Prediction

In [40]:
arr=np.zeros((1,110),dtype=int)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [41]:
new=pd.DataFrame(arr,columns=X_df.columns)
new


year  country_Albania  country_Antigua and Barbuda  country_Argentina  \
0     0                0                            0                  0   

   country_Armenia  country_Aruba  country_Australia  country_Austria  \
0                0              0                  0                0   

   country_Azerbaijan  country_Bahamas  ...  country_Uruguay  \
0                   0                0  ...                0   

   country_Uzbekistan  sex_female  sex_male  age_15-24 years  age_25-34 years  \
0                   0           0         0                0                0   

   age_35-54 years  age_5-14 years  age_55-74 years  age_75+ years  
0                0               0                0              0  

[1 rows x 110 columns]

In [42]:
def convert(year,country,sex,age):
    
    cont=["country"]
    sx=["sex"]
    ag=["age"]
    
#for country

    cont.append(country)
    c="_".join(cont)

#for sex

    sx.append(sex)
    s="_".join(sx)

#for year
    y="year"

#for age

    if age>=5 and age<=14:
        ag.append("5-14 years")
    elif age>=15 and age<=24:
        ag.append("15-24 years")
    elif age>=25 and age<=34:
        ag.append("25-34 years")
    elif age>=35 and age<=54:
        ag.append("35-54 years")
    elif age>=55 and age<=74:
        ag.append("55-74 years")
    elif age>=75:
        ag.append("75+ years")

    a="_".join(ag)
    
    return a,c,s,y


    

In [43]:
country="Albania"
age=55 
sex='male'
year=2001

a,c,s,y=convert(year,country,sex,age)

In [44]:
new[a].replace(0,1,inplace=True)
new[c].replace(0,1,inplace=True)
new[s].replace(0,1,inplace=True)
new[y].replace(0,year,inplace=True)

In [45]:
new

year  country_Albania  country_Antigua and Barbuda  country_Argentina  \
0  2001                1                            0                  0   

   country_Armenia  country_Aruba  country_Australia  country_Austria  \
0                0              0                  0                0   

   country_Azerbaijan  country_Bahamas  ...  country_Uruguay  \
0                   0                0  ...                0   

   country_Uzbekistan  sex_female  sex_male  age_15-24 years  age_25-34 years  \
0                   0           0         1                0                0   

   age_35-54 years  age_5-14 years  age_55-74 years  age_75+ years  
0                0               0                1              0  

[1 rows x 110 columns]

In [46]:
new_arr=np.array(new)

In [47]:
new_arr

array([[2001,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    1,    0,    0,    0,    0,    1,    0]])

In [48]:
rf_regressor.predict(new_arr)

array([5.89033333])

In [49]:
dt_regressor.predict(new_arr)

array([5.59])

In [50]:
lin_regressor.predict(new_arr)

array([12.54135591])

# Web App

In [160]:
ndf=df.groupby(['year','country'],as_index=False)['suicides_no'].sum()
ndf=ndf.reset_index()

In [161]:
app=dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP],assets_ignore='styles.css',
             meta_tags=[{'name':'viewport','content':'width=device-width, initial-scale=1.0'}])

In [162]:
app.layout =dbc.Container([
             html.Div([
                html.H1("Predictions",style={'font-weight':'900'}),
             ],className='pred'),

             html.Div([
                 html.Form([
                          html.H2("Country:",className="name"),    
                          html.Div([
                                    dcc.Dropdown(id="ip_country",multi=False,
                                    options=[{'label':x,'value':x} for x in ndf.sort_values('country')['country'].unique()],
                                    placeholder="Select a country..",style={"background-color":"white"},),
                                   
                         ],id="country",style={"width": "40%"},className="cntdpdn"),
                        
                         
                         html.H2("Year:",className="name"),
                         dcc.Input(id="ip_year",type="number",name="year",style={"width": "40%"},
                                   placeholder="Enter year..",className='yearno'),
                        
                     
                         html.H2("Age:",className='name'),
                         html.Div([
                                   dcc.Dropdown(id="ip_age",multi=False,
                                   options=[{'label':x,'value':x} for x in range(1,121)],
                                   placeholder="Enter age..",style={"background-color":"white"}),
                                   
                         ],id="age",style={"width":"40%"},className="agedpdn"),
                     
                     
                                   
                         html.H2("Gender:",className ='name'),
                         dcc.RadioItems(
                                options=[{'label': 'Male', 'value': 'male'},
                                         {'label': 'Female', 'value': 'female'}],
                                labelStyle={'display': 'inline-block'},
                                id="ip_gender",
                                className="gendradio",
                                inputStyle={"margin-right": "1px","margin-left":'20px',"cursor":"pointer"} 
                         ),
                     
                     
                          html.Button(children=['Submit'], type='button', id='submit_button'),
                         
                          html.H2("Result:",className='name_res'), 
                          html.Div(id="result",className='res'),
                ])
             
             ],className='main',style={"margin-bottom":'50px'})   
                

    ],fluid=True)

In [163]:
@app.callback(
Output("result","children"),
[Input('submit_button','n_clicks')],
[State('ip_year', 'value'),
 State('ip_country', 'value'),
 State('ip_gender', 'value'),
 State('ip_age', 'value')]
)

def convert(n_clicks,year,country,sex,age):
    
    print(type(year))
    yr_str=str(year)
    
    if(len(yr_str)!=4):
        return "Invalid year"
    if(year<=1950 or year>=2100):
        return "Year out of limit.."
    
    
    
    arr=np.zeros((1,110),dtype=int)
    new=pd.DataFrame(arr,columns=X_df.columns)
    
    cont=["country"]
    sx=["sex"]
    ag=["age"]
    
#for country

    cont.append(country)
    c="_".join(cont)

#for sex

    sx.append(sex)
    s="_".join(sx)

#for year
    y="year"

#for age

    if age>=5 and age<=14:
        ag.append("5-14 years")
    elif age>=15 and age<=24:
        ag.append("15-24 years")
    elif age>=25 and age<=34:
        ag.append("25-34 years")
    elif age>=35 and age<=54:
        ag.append("35-54 years")
    elif age>=55 and age<=74:
        ag.append("55-74 years")
    elif age>=75:
        ag.append("75+ years")

    a="_".join(ag)
    
    new[a].replace(0,1,inplace=True)
    new[c].replace(0,1,inplace=True)
    new[s].replace(0,1,inplace=True)
    new[y].replace(0,year,inplace=True)
    
    new_arr=np.array(new)
    
    pred_rate=rf_regressor.predict(new_arr)
    pred_rate=float(pred_rate)
    pred_rate=round(pred_rate,5)
    
    
    return pred_rate
    
    


    

In [ ]:
if __name__=='__main__':
  app.run_server(debug=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [04/Jan/2021 17:53:51] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Jan/2021 17:53:51] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [04/Jan/2021 17:53:51] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [04/Jan/2021 17:53:51] "GET /_favicon.ico?v=1.18.0 HTTP/1.1" 200 -


<class 'NoneType'>
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "f:\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "f:\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\python\lib\site-packages\dash\dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "f:\python\lib\site-packages\dash\d

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "f:\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "f:\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\python\lib\site-packages\dash\dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "f:\python\lib\site-packages\dash\dash.py", line 1007,

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "f:\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "f:\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\python\lib\site-packages\dash\dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "f:\python\lib\site-packages\dash\dash.py", line 1007,

127.0.0.1 - - [04/Jan/2021 17:53:51] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [04/Jan/2021 17:54:02] "POST /_dash-update-component HTTP/1.1" 200 -


<class 'int'>


127.0.0.1 - - [04/Jan/2021 17:54:09] "POST /_dash-update-component HTTP/1.1" 200 -


<class 'int'>


127.0.0.1 - - [04/Jan/2021 17:54:15] "POST /_dash-update-component HTTP/1.1" 200 -


<class 'int'>


127.0.0.1 - - [04/Jan/2021 17:54:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Jan/2021 17:54:16] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [04/Jan/2021 17:54:16] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [04/Jan/2021 17:54:16] "GET /_favicon.ico?v=1.18.0 HTTP/1.1" 200 -


<class 'NoneType'>
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "f:\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "f:\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\python\lib\site-packages\dash\dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "f:\python\lib\site-packages\dash\d

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "f:\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "f:\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\python\lib\site-packages\dash\dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "f:\python\lib\site-packages\dash\dash.py", line 1007,

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "f:\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "f:\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "f:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "f:\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "f:\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\python\lib\site-packages\dash\dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "f:\python\lib\site-packages\dash\dash.py", line 1007,

127.0.0.1 - - [04/Jan/2021 17:54:16] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [04/Jan/2021 17:55:49] "POST /_dash-update-component HTTP/1.1" 200 -


<class 'int'>


127.0.0.1 - - [04/Jan/2021 17:58:41] "POST /_dash-update-component HTTP/1.1" 200 -


<class 'int'>
